package inventarioedd;

import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    // =========================
    // ATRIBUTOS
    // =========================
    private javax.swing.table.DefaultTableModel modeloTabla;
    private ListaProductos lista;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        lista = new ListaProductos();
        ArchivoProductos.cargarProductos(lista);

        modeloTabla = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Nombre", "Categoría", "Cantidad", "Stock mínimo"}, 0
        );
        JTABLEINV.setModel(modeloTabla);
        cargarTabla();

    }

    private void aplicarColoresTabla() {

        JTABLEINV.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                // Columna "Cantidad" → índice 3
                int cantidad = Integer.parseInt(table.getValueAt(row, 3).toString());

                if (!isSelected) {
                    if (cantidad < 5) {
                        c.setBackground(java.awt.Color.PINK); // 🔴 Rojo
                    } else if (cantidad == 5) {
                        c.setBackground(java.awt.Color.YELLOW); // 🟡 Amarillo
                    } else if (cantidad > 10) {
                        c.setBackground(java.awt.Color.GREEN); // 🟢 Verde
                    } else {
                        c.setBackground(java.awt.Color.WHITE); // Normal
                    }
                }

                return c;
            }
        });
    }

// =========================
// ALERTA DE STOCK BAJO
// =========================
    private void verificarStockBajo(Producto p) {
        if (p.getStockMinimo() < 5) {
            JOptionPane.showMessageDialog(
                    this,
                    "⚠ ALERTA: Stock mínimo bajo\n\n"
                    + "Producto: " + p.getNombre()
                    + "\nStock mínimo actual: " + p.getStockMinimo(),
                    "Stock bajo",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }

    // =========================
    // MÉTODO PARA LIMPIAR LOS Jtextfield
    // =========================
    private void limpiarCampos() {
        JTXTID.setText("");
        JTXTN.setText("");
        JTXTCA.setText("");
        JTXTCN.setText("");
        JTXTST.setText("");
        JTXTELI.setText("");
        JTXTBUS.setText("");

        JTXTID.setEnabled(true); // vuelve a permitir ID
    }

    // =========================
    // MÉTODO PARA CARGAR LA TABLA
    // =========================
    private void cargarTabla() {
        modeloTabla.setRowCount(0); // Limpia la tabla

        try {
            java.lang.reflect.Field campo
                    = ListaProductos.class.getDeclaredField("cabeza");
            campo.setAccessible(true);

            NodoProducto actual = (NodoProducto) campo.get(lista);

            while (actual != null) {
                Producto p = actual.dato;

                modeloTabla.addRow(new Object[]{
                    p.getId(),
                    p.getNombre(),
                    p.getCategoria(),
                    p.getCantidad(),
                    p.getStockMinimo()
                });

                actual = actual.siguiente;
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar datos en la tabla",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BTNAGG = new javax.swing.JButton();
        BTNORD = new javax.swing.JButton();
        BTNELI = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JTXTBUS = new javax.swing.JTextField();
        BTNBUS = new javax.swing.JButton();
        JTXTN = new javax.swing.JTextField();
        JTXTID = new javax.swing.JTextField();
        JTXTCN = new javax.swing.JTextField();
        JTXTCA = new javax.swing.JTextField();
        JTXTST = new javax.swing.JTextField();
        JTXTELI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTXTMOD = new javax.swing.JTextField();
        BTNMOD = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTABLEINV = new javax.swing.JTable();

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)), "ProductoID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Categoria");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cantidad");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Stock Minimo");

        BTNAGG.setBackground(new java.awt.Color(102, 255, 102));
        BTNAGG.setForeground(new java.awt.Color(0, 0, 0));
        BTNAGG.setText("Agregar");
        BTNAGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAGGActionPerformed(evt);
            }
        });

        BTNORD.setBackground(new java.awt.Color(153, 255, 255));
        BTNORD.setForeground(new java.awt.Color(0, 0, 0));
        BTNORD.setText("Ordenar");
        BTNORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNORDActionPerformed(evt);
            }
        });

        BTNELI.setBackground(new java.awt.Color(204, 0, 0));
        BTNELI.setForeground(new java.awt.Color(0, 0, 0));
        BTNELI.setText("Eliminar");
        BTNELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNELIActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Buscar ID");

        JTXTBUS.setBackground(new java.awt.Color(255, 255, 255));
        JTXTBUS.setForeground(new java.awt.Color(0, 0, 0));
        JTXTBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTBUSActionPerformed(evt);
            }
        });

        BTNBUS.setBackground(new java.awt.Color(255, 255, 102));
        BTNBUS.setForeground(new java.awt.Color(0, 0, 0));
        BTNBUS.setText("Buscar");
        BTNBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSActionPerformed(evt);
            }
        });

        JTXTN.setBackground(new java.awt.Color(255, 255, 255));
        JTXTN.setForeground(new java.awt.Color(0, 0, 0));
        JTXTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTNActionPerformed(evt);
            }
        });

        JTXTID.setBackground(new java.awt.Color(255, 255, 255));
        JTXTID.setForeground(new java.awt.Color(0, 0, 0));
        JTXTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTIDActionPerformed(evt);
            }
        });

        JTXTCN.setBackground(new java.awt.Color(255, 255, 255));
        JTXTCN.setForeground(new java.awt.Color(0, 0, 0));
        JTXTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTCNActionPerformed(evt);
            }
        });

        JTXTCA.setBackground(new java.awt.Color(255, 255, 255));
        JTXTCA.setForeground(new java.awt.Color(0, 0, 0));
        JTXTCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTCAActionPerformed(evt);
            }
        });

        JTXTST.setBackground(new java.awt.Color(255, 255, 255));
        JTXTST.setForeground(new java.awt.Color(0, 0, 0));
        JTXTST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTSTActionPerformed(evt);
            }
        });

        JTXTELI.setBackground(new java.awt.Color(255, 255, 255));
        JTXTELI.setForeground(new java.awt.Color(0, 0, 0));
        JTXTELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTELIActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Eliminar ID");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Modificar ID");

        JTXTMOD.setBackground(new java.awt.Color(255, 255, 255));
        JTXTMOD.setForeground(new java.awt.Color(0, 0, 0));
        JTXTMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTMODActionPerformed(evt);
            }
        });

        BTNMOD.setBackground(new java.awt.Color(255, 153, 51));
        BTNMOD.setForeground(new java.awt.Color(0, 0, 0));
        BTNMOD.setText("Modificar");
        BTNMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMODActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BTNAGG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNORD)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTXTST, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(JTXTCN)
                            .addComponent(JTXTCA)
                            .addComponent(JTXTN)
                            .addComponent(JTXTID))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTXTBUS)
                            .addComponent(JTXTELI))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNELI)
                            .addComponent(BTNBUS)
                            .addComponent(BTNMOD))
                        .addGap(10, 10, 10))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(JTXTMOD, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(JTXTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTXTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTXTCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTXTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTXTST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNAGG)
                    .addComponent(BTNORD))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTXTBUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBUS))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXTMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(BTNMOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNELI)
                    .addComponent(JTXTELI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)), "Inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        JTABLEINV.setBackground(new java.awt.Color(255, 255, 255));
        JTABLEINV.setForeground(new java.awt.Color(0, 0, 0));
        JTABLEINV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoria", "Cantidad", "Stock Minimo"
            }
        ));
        jScrollPane2.setViewportView(JTABLEINV);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSActionPerformed
        try {
            int id = Integer.parseInt(JTXTBUS.getText());
            Producto p = lista.buscarProducto(id);

            // Limpiar tabla antes de mostrar resultado
            modeloTabla.setRowCount(0);

            if (p == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "El producto no existe",
                        "Buscar",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            // Advertencia si no hay existencias
            if (p.getCantidad() <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "El producto no tiene existencias",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
            }

            // Mostrar en la tabla
            modeloTabla.addRow(new Object[]{
                p.getId(),
                p.getNombre(),
                p.getCategoria(),
                p.getCantidad(),
                p.getStockMinimo()
            });

            // 🔹 RELLENAR CAMPOS AUTOMÁTICAMENTE 🔹
            JTXTID.setText(String.valueOf(p.getId()));
            JTXTN.setText(p.getNombre());
            JTXTCA.setText(p.getCategoria());
            JTXTCN.setText(String.valueOf(p.getCantidad()));
            JTXTST.setText(String.valueOf(p.getStockMinimo()));

            // Bloquear ID para evitar modificaciones
            JTXTID.setEnabled(false);

            verificarStockBajo(p);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un ID válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BTNBUSActionPerformed

    private void JTXTBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTBUSActionPerformed

    private void BTNORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNORDActionPerformed
        BTNORD.addActionListener(e -> {
            lista.ordenarPorIdInsercion();
            ArchivoProductos.guardarProductos(lista);
            cargarTabla();
        });
    }//GEN-LAST:event_BTNORDActionPerformed

    private void BTNAGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAGGActionPerformed
        try {

            int id = Integer.parseInt(JTXTID.getText());
            String nombre = JTXTN.getText();
            String categoria = JTXTCA.getText();
            int cantidad = Integer.parseInt(JTXTCN.getText());
            int stock = Integer.parseInt(JTXTST.getText());

            if (lista.buscarProducto(id) != null) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Ya existe un producto con ese ID",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (id <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "El ID debe ser un número mayor que cero",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (stock > cantidad) {
                JOptionPane.showMessageDialog(
                        this,
                        "El stock mínimo no puede ser mayor que la cantidad actual",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cantidad <= 0 || stock <= 0) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "La cantidad y el stock mínimo deben ser mayores que cero",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            Producto p = new Producto(id, nombre, categoria, cantidad, stock);
            lista.agregarProducto(p);
            ArchivoProductos.guardarProductos(lista);

            cargarTabla();
            verificarStockBajo(p);
            limpiarCampos();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Datos inválidos",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BTNAGGActionPerformed

    private void JTXTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTNActionPerformed

    private void JTXTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTIDActionPerformed

    private void JTXTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTCNActionPerformed

    private void JTXTCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTCAActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void JTXTSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTSTActionPerformed

    private void JTXTELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTELIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTELIActionPerformed

    private void BTNELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNELIActionPerformed
        try {
            int id = Integer.parseInt(JTXTELI.getText());

            boolean eliminado = lista.eliminarProducto(id);

            if (!eliminado) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Producto no encontrado",
                        "Eliminar",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            ArchivoProductos.guardarProductos(lista);
            cargarTabla();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Producto eliminado correctamente",
                    "Eliminar",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "ID inválido",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNELIActionPerformed

    private void JTXTMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTMODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTMODActionPerformed

    private void BTNMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMODActionPerformed
        try {
            int idBuscar = Integer.parseInt(JTXTMOD.getText());
            String nombre = JTXTN.getText();
            String categoria = JTXTCA.getText();
            int cantidad = Integer.parseInt(JTXTCN.getText());
            int stock = Integer.parseInt(JTXTST.getText());

            // =========================
            // VALIDACIONES
            // =========================
            if (idBuscar <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El ID a modificar debe ser mayor que cero",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (cantidad <= 0 || stock <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Cantidad y stock mínimo deben ser mayores que cero",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (stock > cantidad) {
                JOptionPane.showMessageDialog(this,
                        "El stock mínimo no puede ser mayor que la cantidad",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean modificado = lista.modificarProducto(
                    idBuscar, nombre, categoria, cantidad, stock);

            if (!modificado) {
                JOptionPane.showMessageDialog(this,
                        "No existe un producto con ese ID",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // =========================
            // GUARDAR Y ACTUALIZAR
            // =========================
            ArchivoProductos.guardarProductos(lista);
            cargarTabla();

            // 🔴 ALERTA DE STOCK BAJO
            Producto p = lista.buscarProducto(idBuscar);
            verificarStockBajo(p);

            limpiarCampos();

            JOptionPane.showMessageDialog(this,
                    "Producto modificado correctamente",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Datos inválidos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNMODActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAGG;
    private javax.swing.JButton BTNBUS;
    private javax.swing.JButton BTNELI;
    private javax.swing.JButton BTNMOD;
    private javax.swing.JButton BTNORD;
    private javax.swing.JTable JTABLEINV;
    private javax.swing.JTextField JTXTBUS;
    private javax.swing.JTextField JTXTCA;
    private javax.swing.JTextField JTXTCN;
    private javax.swing.JTextField JTXTELI;
    private javax.swing.JTextField JTXTID;
    private javax.swing.JTextField JTXTMOD;
    private javax.swing.JTextField JTXTN;
    private javax.swing.JTextField JTXTST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
